import type { Exercise } from './types';

export const SEED_EXERCISES: Exercise[] = [
  {
    id: 'wall-slides',
    name: 'Wall slides',
    category: 'activation',
    order: 1,
    progressionNotes:
      'Wall slides are the most likely exercise to aggravate the affected shoulder if there is active sensitization. Default to Level 1 or 2 unless you know you can do more. Pain in the upper shoulder during or after means drop a level. Mild work in mid-back / serratus means you are at the right level.',
    levels: [
      {
        level: 1,
        name: 'Scapular wall taps',
        description: [
          'Stand facing the wall, arms straight, palms flat at shoulder height.',
          'Push through your hands so your upper back rounds and your shoulder blades spread (protraction).',
          'Pull your shoulder blades back together (retraction).',
          'Arms stay straight the whole time — all the movement is at the shoulder blades.',
        ],
        cueText: 'Push the wall away, then pull it toward you, all at the shoulder blades. Arms stay straight.',
        failureModes: [
          'Bending the elbows',
          'Using neck or upper traps to assist',
          'Spine rotating to help',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: '2x10 with clean protraction/retraction, no upper trap engagement, no shoulder pain during or after.',
      },
      {
        level: 2,
        name: 'Wall slide — partial range',
        description: [
          'Stand with your back against the wall. Heels 4–6 inches out. Tailbone, lower back, upper back, and head all touching the wall.',
          'Arms in goalpost: elbows bent 90°, backs of hands and forearms pressed flat against the wall at shoulder height.',
          'Slide forearms up the wall only as far as the elbows can go without forearms peeling off or shoulders shrugging — often only 6–10 inches.',
          'Slide back down to start with control.',
        ],
        cueText: 'Tiny range, perfect form. Stop the moment anything breaks down.',
        failureModes: [
          'Forearms peel off the wall',
          'Shoulders shrug up',
          'Lumbar gap opens (low back leaves the wall)',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: '2x10 at this partial range with no compensation, work felt in mid-back / serratus, no upper-trap soreness.',
      },
      {
        level: 3,
        name: 'Wall slide — three-quarter range',
        description: [
          'Same setup as Level 2, back against the wall.',
          'Slide arms up to roughly the position where your elbows reach forehead height.',
          'Slide back down to the goalpost start.',
          'Maintain all wall contact and a quiet upper back the whole way.',
        ],
        cueText: 'Tiny range, perfect form. Stop the moment anything breaks down.',
        failureModes: [
          'Forearms peel off',
          'Shoulders shrug',
          'Low back arches',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Clean reps at this range, no upper-trap dominance during or after.',
      },
      {
        level: 4,
        name: 'Wall slide — full range',
        description: [
          'Same setup, back against wall.',
          'Slide arms up to full overhead extension while maintaining all wall constraints — wrists, elbows, head, upper back, low back all stay on the wall.',
          'Slide back down to goalpost.',
        ],
        cueText: 'Long lats, heavy shoulders, ribs down.',
        failureModes: [
          'Lumbar arch increases at the top',
          'Forearms come off the wall at the top',
          'Shoulders shrug at the top',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Full range with all constraints maintained for 2x10.',
      },
      {
        level: 5,
        name: 'Loaded wall slide',
        description: [
          'Set up as Level 4. Add a small foam roller or rolled towel between forearms and wall, OR hold a light band between hands pulling outward.',
          'Slide through full range while keeping the roller pinned (or band tensioned) the entire time.',
          'This adds serratus and external-rotation demand on top of the base movement.',
        ],
        cueText: 'Push the foam roller into the wall throughout the slide (or keep the band pulled apart the entire time).',
        failureModes: [
          'Roller drops or band collapses inward',
          'Original wall constraints fail',
          'Shoulders shrug to maintain the load',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Endpoint — stay here for maintenance.',
      },
    ],
  },
  {
    id: 'prone-ytw',
    name: 'Prone scapular series',
    category: 'activation',
    order: 2,
    progressionNotes:
      'The single most common failure mode is "I cannot lift my arm with my back muscles" — meaning you are at Level 1 or 2 even though the textbook prescription is Level 4. Default to Level 1 unless you can demonstrate Level 2+ cleanly.',
    levels: [
      {
        level: 1,
        name: 'Supine floor angels',
        description: [
          'Lie on your back, knees bent, feet flat.',
          'Arms in a goalpost — elbows bent 90°, backs of forearms and hands trying to stay on the floor.',
          'Slide arms slowly overhead and back down, keeping the backs of forearms and hands in contact with the floor the whole time.',
          'Stop the moment forearms peel up or your low back arches off the floor.',
        ],
        cueText: 'Backs of hands and forearms stay heavy on the floor.',
        failureModes: [
          'Lower back arches off the floor',
          'Forearms peel up',
          'Shoulders shrug toward ears',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Full range with forearms maintaining floor contact and lower back staying down.',
      },
      {
        level: 2,
        name: 'Prone Y on incline',
        description: [
          'Lie face down on a couch, ottoman, or sturdy bed with your chest at the edge so arms can hang off.',
          'Lift arms in a Y position (thumbs up, arms in a wide V overhead) only as far as the back muscles can lift them — likely a small range.',
          'Pause briefly at the top, then lower with control.',
        ],
        cueText: 'Lift from below the shoulder blade, not from the arm. Tiny range is fine.',
        failureModes: [
          'Using momentum to swing the arms up',
          'Shrugging the shoulders',
          'Lifting too high so the upper trap takes over',
        ],
        defaultSets: 2,
        defaultReps: 8,
        graduationCriteria: 'Lift to roughly arm-parallel-to-floor with the back doing the work, no upper-trap engagement.',
      },
      {
        level: 3,
        name: 'Single-arm prone Y, off bed/table',
        description: [
          'Lie face down on a bed or sturdy table with one arm hanging off the side.',
          'With your free hand, place fingers on the muscle below the working shoulder blade — feel it engage before you lift.',
          'Lift the arm in a Y position, focusing on isolating the lower trap.',
          'Switch sides after the prescribed reps.',
        ],
        cueText: 'Find the muscle below the shoulder blade with your other hand — feel it fire before you lift.',
        failureModes: [
          'Same as Level 2',
          'Rotating the torso to assist the lift',
        ],
        defaultSets: 2,
        defaultReps: '8 each side',
        graduationCriteria: 'Lift each arm cleanly with isolated back engagement on both sides.',
      },
      {
        level: 4,
        name: 'Prone Y-T-W on floor (partial range)',
        description: [
          'Lie face down on the floor, forehead on a rolled towel. Engage glutes lightly to keep low back neutral.',
          'Y: arms at ~30° overhead, thumbs up. Lift from the back, hold 1–2 seconds, lower.',
          'T: arms straight to the sides at 90°, thumbs up. Lift, hold, lower.',
          'W: elbows at sides, forearms forward. Lift hands by retracting shoulder blades, hold, lower.',
          'One rep = all three positions. Lift only as high as the back muscles can manage cleanly — even half an inch is fine.',
        ],
        cueText: 'Movement should be tiny. Quality over height.',
        failureModes: [
          'Cranking arms up with momentum',
          'Shrugging',
          'Arching the low back',
        ],
        defaultSets: 2,
        defaultReps: '8 each',
        graduationCriteria: 'Clean reps at any range, all three positions, with the back muscles clearly doing the work.',
      },
      {
        level: 5,
        name: 'Prone Y-T-W on floor — full range, light load',
        description: [
          'Same setup and execution as Level 4.',
          'Lift hands 2–4 inches off the floor (full intended range).',
          'Hold 2–5 lb dumbbells in each hand.',
        ],
        cueText: 'Movement should be tiny — even with load. Quality over height.',
        failureModes: [
          'Same as Level 4 — momentum, shrugging, low-back arch',
        ],
        defaultSets: 2,
        defaultReps: '8 each',
        graduationCriteria: 'Endpoint — stay here for maintenance, can add load slowly over time.',
      },
    ],
  },
  {
    id: 'serratus-slide',
    name: 'Serratus anterior progression',
    category: 'activation',
    order: 3,
    progressionNotes:
      'Serratus is often very weak in chronic upper trap dominance because the upper trap has been doing its job. Quadruped is genuinely useful even for stronger users — sometimes the issue is not strength but motor pattern access. Do not skip Level 1 if you cannot feel serratus working at Level 2.',
    levels: [
      {
        level: 1,
        name: 'Quadruped scapular push-up',
        description: [
          'On hands and knees, hands directly under shoulders, arms straight throughout.',
          'Let your chest sink between your shoulder blades (retraction).',
          'Push the floor away so your upper back rounds (protraction). Arms stay locked straight.',
          'Repeat — all the movement is at the shoulder blades.',
        ],
        cueText: 'Arms locked straight. All the movement happens at the shoulder blades.',
        failureModes: [
          'Bending the elbows',
          'Rocking the hips',
          'Using the neck',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Clean protraction-retraction at quadruped, can feel serratus working.',
      },
      {
        level: 2,
        name: 'Wall serratus slide',
        description: [
          'Face the wall, feet about 12 inches away. Forearms vertical against the wall, elbows at shoulder height, hands above elbows.',
          'Push your forearms hard into the wall and reach your shoulder blades forward (protraction). Upper back should round slightly.',
          'Maintaining that press, slide your forearms slowly up the wall.',
          'Slide back down with continuous pressure into the wall the entire time.',
        ],
        cueText: 'Push the wall away as you slide up.',
        failureModes: [
          'Hunching the head forward',
          'Shrugging up',
          'Losing the protraction',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Full slide range with protraction maintained throughout.',
      },
      {
        level: 3,
        name: 'Incline push-up plus',
        description: [
          'Hands on a sturdy elevated surface (kitchen counter, sturdy bench).',
          'Do a regular push-up.',
          'At the top, push the surface away further so your upper back rounds — this is the "plus".',
          'Lower with control and repeat.',
        ],
        cueText: 'Reach the surface away from you at the top.',
        failureModes: [
          'Skipping the plus',
          'Shrugging',
          'Hips sagging',
        ],
        defaultSets: 2,
        defaultReps: 10,
        graduationCriteria: 'Clean plus on each rep at this incline.',
      },
      {
        level: 4,
        name: 'Floor push-up plus',
        description: [
          'Standard push-up plank position.',
          'Do a push-up.',
          'At the top, push the floor away so your upper back rounds.',
          'Maintain a strong line from head to heels the whole rep.',
        ],
        cueText: 'Reach the floor away from you at the top.',
        failureModes: [
          'Skipping the plus',
          'Shrugging',
          'Losing core or hip alignment as load increases',
        ],
        defaultSets: 2,
        defaultReps: 8,
        graduationCriteria: 'Endpoint — can add reps or sets for maintenance.',
      },
    ],
  },
  {
    id: 'band-pull-aparts',
    name: 'Band pull-aparts',
    category: 'integration',
    order: 4,
    progressionNotes:
      'Usually one of the lower-risk exercises. Most people can start at Level 1 or 2 without issues. If shrugging is unavoidable even with a light band, it is not really a band problem — it is a deeper motor pattern issue, and the activation exercises (wall slides, Y-T-W) need more work first.',
    levels: [
      {
        level: 1,
        name: 'Light band, palms down, chest level',
        description: [
          'Stand tall, feet hip-width.',
          'Hold a light resistance band with both hands, palms facing down.',
          'Arms straight out in front at shoulder height, hands shoulder-width on the band.',
          'Pull the band apart until it touches your chest, then return slowly.',
        ],
        cueText: 'Squeeze mid-back, no shrugging, long neck throughout.',
        failureModes: [
          'Shrugging',
          'Bending the elbows',
          'Using a band that is too heavy',
        ],
        defaultSets: 2,
        defaultReps: 15,
        graduationCriteria: '2x15 with clean form, no shrug, can feel mid-back working.',
      },
      {
        level: 2,
        name: 'Light band, palms up',
        description: [
          'Same setup as Level 1 but with palms facing up (supinated grip).',
          'This adds an external-rotation component, increasing rear-delt and rotator-cuff engagement.',
          'Pull apart, return slowly.',
        ],
        cueText: 'Lead with pinkies. Squeeze mid-back, no shrugging.',
        failureModes: [
          'Shrugging',
          'Bending the elbows',
        ],
        defaultSets: 2,
        defaultReps: 15,
        graduationCriteria: '2x15 with the supinated grip and clean form.',
      },
      {
        level: 3,
        name: 'Heavier band, palms up, with hold',
        description: [
          'Heavier resistance band, palms facing up.',
          'Pull apart, hold for 2 seconds at the end position, return slowly.',
        ],
        cueText: 'Lead with pinkies. Hold the squeeze at the end without shrugging.',
        failureModes: [
          'Shrugging',
          'Bending the elbows',
          'Form falling apart during the hold',
        ],
        defaultSets: 2,
        defaultReps: 12,
        graduationCriteria: 'Endpoint — maintenance level.',
      },
    ],
  },
  {
    id: 'face-pulls',
    name: 'Face pulls',
    category: 'integration',
    order: 5,
    progressionNotes:
      'An integration exercise — it puts the whole pattern together under load. Do not push to Level 2 or 3 if the underlying activation work is not solid. If you are at Level 1–2 of wall slides or Y-T-W, stay at Level 1 here.',
    levels: [
      {
        level: 1,
        name: 'Band face pull, no rotation',
        description: [
          'Anchor a band at forehead height (door anchor, pull-up bar, etc.).',
          'Step back so there is light tension with arms straight forward.',
          'Pull the band toward your forehead, leading with your elbows out wide.',
          'No hand rotation at the end — keep palms down.',
          'Return slowly with control.',
        ],
        cueText: 'Elbows out wide. Squeeze mid-back.',
        failureModes: [
          'Shrugging',
          'Pulling with the arms only, scapula static',
          'Using the neck',
        ],
        defaultSets: 2,
        defaultReps: 12,
        graduationCriteria: 'Clean face pulls without compensation.',
      },
      {
        level: 2,
        name: 'Band face pull with external rotation',
        description: [
          'Same setup as Level 1.',
          'Pull the band toward your face, leading with the elbows.',
          'As your hands approach your face, rotate your forearms up so your knuckles end up pointing at the ceiling.',
          'End position: elbows high (slightly above shoulders), hands higher than elbows — like a double biceps pose.',
          'Reverse the motion slowly.',
        ],
        cueText: 'Elbows high, hands higher. Shoulder blades retract first, then elbows pull, then hands rotate up.',
        failureModes: [
          'Skipping the external rotation at the end',
          'Shrugging during the pull',
          'Pulling with the arms only',
        ],
        defaultSets: 2,
        defaultReps: 12,
        graduationCriteria: 'Clean reps with full external rotation, no shrug.',
      },
      {
        level: 3,
        name: 'Cable face pull, slow eccentric',
        description: [
          'Same movement at a cable machine with adjustable load.',
          'Use a 3-second eccentric (return phase) on every rep.',
          'Progressive load over time as form holds.',
        ],
        cueText: 'Same end position. Slow on the way back — control the load.',
        failureModes: [
          'Skipping the external rotation',
          'Shrugging',
          'Rushing the eccentric',
        ],
        defaultSets: 2,
        defaultReps: 12,
        graduationCriteria: 'Endpoint — maintenance, can progressively add load.',
      },
    ],
  },
];
